name: CI & Security Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          pwd
          ls -la ..
          ls -la ../medusa-storefront || echo "medusa-storefront not found"
          ls -la ../my-medusa-store || echo "my-medusa-store not found"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # === Backend ===
      - name: Install backend dependencies
        working-directory: ../my-medusa-store
        run: npm install

      - name: Set up .env for backend
        working-directory: ../my-medusa-store
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres" > .env
          echo "REDIS_URL=redis://localhost:6379" >> .env
          echo "JWT_SECRET=supersecret" >> .env
          echo "COOKIE_SECRET=supersecret" >> .env

      - name: Prepare Medusa DB
        working-directory: ../my-medusa-store
        run: |
          npx medusa db:create
          npx medusa db:migrate

      - name: Run backend tests
        working-directory: ../my-medusa-store
        run: npm test || echo "No backend tests"

      # === Frontend ===
      - name: Install frontend dependencies
        working-directory: ../medusa-storefront
        run: npm install

      - name: Lint frontend
        working-directory: ../medusa-storefront
        run: npm run lint || echo "Lint issues"

      - name: Run frontend tests
        working-directory: ../medusa-storefront
        run: npm test || echo "No frontend tests"

  # === Trivy Scan ===
  trivy:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  # === SonarQube Scan ===
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # === OWASP Dependency Check ===
  owasp:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Webshop'
          path: '.'
          format: 'ALL'
          out: 'reports'
